# Generated by Django 3.2.18 on 2023-04-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230426_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('산', '산'), ('바다', '바다'), ('계곡', '계곡'), ('섬', '섬')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
