# Generated by Django 3.2.18 on 2023-05-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='vote',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('soso', 'Soso')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Emote',
        ),
    ]
